node {
    def mvnHome
    stage('Preparation') { 
        
        git 'https://github.com/quick-aib/docker-java.git'
        
        mvnHome = tool 'M3'
    }
    stage('Build') {
        
        withEnv(["MVN_HOME=$mvnHome"]) {
            if (isUnix()) {
                sh '"$MVN_HOME/bin/mvn" -f docker-spring-boot/pom.xml -Dmaven.test.failure.ignore clean package'
            } else {
                bat(/"%MVN_HOME%\bin\mvn" -Dmaven.test.failure.ignore clean package/)
            }
        }
    }
    stage('Results') {
       echo "docker build"
    }
}
