# kubectl create ns dev
# kubectl run spring-boot --image=spring-boot --port=80
# kubectl expose pod n1 --port=81 --target-port=80 –nodePort=31709 --name=svc1 --type=NodePort
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
  labels:
    app: spring-boot
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      name: n1
      labels:
        app: spring-boot
      namespace: dev
    spec:
      containers:
      - name: spring-boot
        image: "devopsjuly22017/spring-boot:1.0 "
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-bootsvc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: spring-boot
  ports:
  - protocol: TCP
    port: 81
    targetPort: 8080
    nodePort: 31711

  
